# Generated by Django 4.0.4 on 2022-05-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
    ]
