# Generated by Django 4.0.4 on 2022-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_rename_fecha_nacimiento_persona_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.SmallIntegerField(default=1),
        ),
    ]
