# Generated by Django 4.0.4 on 2022-06-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_altura'),
        ('familia', '0004_persona_edad'),
    ]

    operations = [
    ]
