# Generated by Django 4.0.4 on 2022-06-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_merge_0003_persona_altura_0004_persona_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
    ]
